[general]
  import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
  ]

[window]
  opacity = 0.97
  decorations = "None"

[font]
  size = 14.0
  normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
