[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[window]
opacity = 0.97
decorations = "None"

[window.padding]
x = 15
y = 10

[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
