[env]
TERM = "xterm-256color"

[general]
  import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
  ]

[window]
  opacity = 0.97
  decorations = "None"

[window.padding]
x = 15
y = 10

[font]
  size = 12.0
  normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
